FROM python/python:3.11-slim

WORKDIR /workspace

RUN pip install -r "torch-reqs.txt" --no-cache-dir

RUN pip install git+https://github.com/KellerJordan/Muon --no-cache-dir

RUN pip install flash-attn --no-build-isolation

RUN pip install -r requirements.txt --no-cache-dir

CMD ["sleep", "infinity"]
