services:
  trainer:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.trainer
    entrypoint: ""
    volumes:
      - ".:/workspace"
    command: ["shell/train_model.sh"]

  inference:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.vllm
    volumes:
      - ".:/workspace"
    command: ["shell/eval_model.sh"]

  notebook:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.notebook
    volumes:
      - ".:/app"
    ports:
      - "8889:8888"
