FROM python/python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --no-cache-dir jupyter ipykernel

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
